techtree = {9: {'cost_gas': 25,
  'cost_mineral': 25,
  'id': 9,
  'is_building': False,
  'morph_from_id': [105, 151],
  'name': 'Baneling',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [96, 89, 86],
  'size': 0,
  'supply': 0.5},
 12: {'cost_gas': 0,
  'cost_mineral': 0,
  'id': 12,
  'is_building': False,
  'morph_from_id': [129],
  'name': 'Changeling',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [100, 89, 86],
  'size': 0,
  'supply': 0},
 86: {'cost_gas': 0,
  'cost_mineral': 300,
  'id': 86,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'Hatchery',
  'needs_coord': True,
  'needs_creep': False,
  'requirement': [],
  'size': 5,
  'supply': -6},
 87: {'cost_gas': 0,
  'cost_mineral': 25,
  'id': 87,
  'is_building': True,
  'morph_from_id': [126, 151],
  'name': 'CreepTumor',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [],
  'size': 1,
  'supply': 0},
 88: {'cost_gas': 0,
  'cost_mineral': 25,
  'id': 88,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'Extractor',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [],
  'size': 3,
  'supply': 0},
 89: {'cost_gas': 0,
  'cost_mineral': 200,
  'id': 89,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'SpawningPool',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [86],
  'size': 3,
  'supply': 0},
 90: {'cost_gas': 0,
  'cost_mineral': 25,
  'id': 90,
  'is_building': True,
  'morph_from_id': [86, 104, 151],
  'name': 'EvolutionChamber',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [86],
  'size': 3,
  'supply': 0},
 91: {'cost_gas': 100,
  'cost_mineral': 100,
  'id': 91,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'HydraliskDen',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [100, 89, 86],
  'size': 3,
  'supply': 0},
 92: {'cost_gas': 200,
  'cost_mineral': 200,
  'id': 92,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'Spire',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [100, 89, 86],
  'size': 2,
  'supply': 0},
 93: {'cost_gas': 200,
  'cost_mineral': 150,
  'id': 93,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'UltraliskCavern',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [101, 94, 100, 89, 86],
  'size': 3,
  'supply': 0},
 94: {'cost_gas': 100,
  'cost_mineral': 100,
  'id': 94,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'InfestationPit',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [100, 89, 86],
  'size': 3,
  'supply': 0},
 95: {'cost_gas': 150,
  'cost_mineral': 150,
  'id': 95,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'NydusNetwork',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [100, 89, 86],
  'size': 3,
  'supply': 0},
 96: {'cost_gas': 50,
  'cost_mineral': 100,
  'id': 96,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'BanelingNest',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [89, 86],
  'size': 3,
  'supply': 0},
 97: {'cost_gas': 0,
  'cost_mineral': 150,
  'id': 97,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'RoachWarren',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [89, 86],
  'size': 3,
  'supply': 0},
 98: {'cost_gas': 0,
  'cost_mineral': 100,
  'id': 98,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'SpineCrawler',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [89, 86],
  'size': 2,
  'supply': 0},
 99: {'cost_gas': 0,
  'cost_mineral': 75,
  'id': 99,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'SporeCrawler',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [89, 86],
  'size': 2,
  'supply': 0},
 100: {'cost_gas': 100,
  'cost_mineral': 150,
  'id': 100,
  'is_building': True,
  'morph_from_id': [86, 104, 151],
  'name': 'Lair',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [89, 86],
  'size': 5,
  'supply': -6},
 101: {'cost_gas': 150,
  'cost_mineral': 200,
  'id': 101,
  'is_building': True,
  'morph_from_id': [100, 86, 104, 151],
  'name': 'Hive',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [94, 89, 86],
  'size': 5,
  'supply': -6},
 102: {'cost_gas': 150,
  'cost_mineral': 100,
  'id': 102,
  'is_building': True,
  'morph_from_id': [92, 104, 151],
  'name': 'GreaterSpire',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [92, 101, 94, 100, 89, 86],
  'size': 2,
  'supply': 0},
 104: {'cost_gas': 0,
  'cost_mineral': 50,
  'id': 104,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Drone',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [151],
  'size': 0,
  'supply': 1},
 105: {'cost_gas': 0,
  'cost_mineral': 25,
  'id': 105,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Zergling',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [89],
  'size': 0,
  'supply': 0.5},
 106: {'cost_gas': 0,
  'cost_mineral': 100,
  'id': 106,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Overlord',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [151],
  'size': 0,
  'supply': -8},
 107: {'cost_gas': 50,
  'cost_mineral': 100,
  'id': 107,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Hydralisk',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [100, 89, 86],
  'size': 0,
  'supply': 2},
 108: {'cost_gas': 100,
  'cost_mineral': 100,
  'id': 108,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Mutalisk',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [],
  'size': 0,
  'supply': 2},
 109: {'cost_gas': 200,
  'cost_mineral': 300,
  'id': 109,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Ultralisk',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [93, 101, 94, 100, 89, 86],
  'size': 0,
  'supply': 6},
 110: {'cost_gas': 25,
  'cost_mineral': 75,
  'id': 110,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Roach',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [97, 89, 86],
  'size': 0,
  'supply': 2},
 111: {'cost_gas': 150,
  'cost_mineral': 100,
  'id': 111,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Infestor',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [94, 100, 89, 86],
  'size': 0,
  'supply': 2},
 112: {'cost_gas': 100,
  'cost_mineral': 150,
  'id': 112,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Corruptor',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [92, 100, 89, 86],
  'size': 0,
  'supply': 2},
 114: {'cost_gas': 150,
  'cost_mineral': 150,
  'id': 114,
  'is_building': False,
  'morph_from_id': [112, 151],
  'name': 'BroodLord',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [102, 92, 101, 94, 100, 89, 86],
  'size': 0,
  'supply': 4},
 126: {'cost_gas': 0,
  'cost_mineral': 150,
  'id': 126,
  'is_building': False,
  'morph_from_id': [86, 104, 151],
  'name': 'Queen',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [89],
  'size': 0,
  'supply': 2},
 129: {'cost_gas': 50,
  'cost_mineral': 50,
  'id': 129,
  'is_building': False,
  'morph_from_id': [106, 151],
  'name': 'Overseer',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [100, 89, 86],
  'size': 0,
  'supply': -8},
 142: {'cost_gas': 75,
  'cost_mineral': 75,
  'id': 142,
  'is_building': True,
  'morph_from_id': [95, 104, 151],
  'name': 'NydusWorm',
  'needs_coord': False,
  'needs_creep': True,
  'requirement': [95, 100, 89, 86],
  'size': 3,
  'supply': 0},
 151: {'cost_gas': 0,
  'cost_mineral': 50,
  'id': 151,
  'is_building': False,
  'morph_from_id': [],
  'name': 'Larva',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [],
  'size': 0,
  'supply': 0},
 289: {'cost_gas': 0,
  'cost_mineral': 0,
  'id': 289,
  'is_building': False,
  'morph_from_id': [114, 112, 151],
  'name': 'Broodling',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [1, 3, 14, 8, 9],
  'size': 0,
  'supply': 0},
 489: {'cost_gas': 0,
  'cost_mineral': 0,
  'id': 489,
  'is_building': False,
  'morph_from_id': [494, 151],
  'name': 'Locust',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [94, 100, 89, 86],
  'size': 0,
  'supply': 0},
 494: {'cost_gas': 75,
  'cost_mineral': 100,
  'id': 494,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'SwarmHost',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [94, 100, 89, 86],
  'size': 0,
  'supply': 3},
 499: {'cost_gas': 200,
  'cost_mineral': 100,
  'id': 499,
  'is_building': False,
  'morph_from_id': [151],
  'name': 'Viper',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [86],
  'size': 0,
  'supply': 3},
 502: {'cost_gas': 100,
  'cost_mineral': 50,
  'id': 502,
  'is_building': False,
  'morph_from_id': [107, 151],
  'name': 'Lurker',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [504, 91, 100, 89, 86],
  'size': 3,
  'supply': 3},
 504: {'cost_gas': 150,
  'cost_mineral': 100,
  'id': 504,
  'is_building': True,
  'morph_from_id': [104, 151],
  'name': 'LurkerDen',
  'needs_coord': True,
  'needs_creep': True,
  'requirement': [91, 100, 89, 86],
  'size': 3,
  'supply': 0},
 688: {'cost_gas': 75,
  'cost_mineral': 25,
  'id': 688,
  'is_building': False,
  'morph_from_id': [110, 151],
  'name': 'Ravager',
  'needs_coord': False,
  'needs_creep': False,
  'requirement': [97, 89, 86],
  'size': 0,
  'supply': 3}}